### PR TITLE
Fix/mt51

### LINKED ISSUE #45: Fe54 LRF=7 evaluation from ENDF/B-VIII.0 does not reconstruct inelastic scattering
MT51 leads to non-zero cross sections in one of the 5 Fe57 spin groups. In tests prior to changes in the fromENDF function related to duplicate spin groups, inelastic scattering was included. After the changes, it appeared to be missing.

The issue was traced back to the erroneous size of a number of ranges used in creating the ParticleChannelData objects that are used to populate the ComoundSystem.

### PR DESCRIPTION
**Pull request by whaeck**
This fixes #45 

Pull request #44 should be merged prior to this one to make the reviewer's life easier.

### CODE REVIEW

File: src/resonanceReconstruction/rmatrix/legacy/SpinGroupBase/src/makeReactionIdentifiers.hpp [hunk 1]
```diff
@@ -11,11 +11,12 @@ makeReactionIdentifiers( const Channel< Neutron >& channel,
...
+  // lambdas
+  auto hasFission = [] ( const auto& resonance )
+                       { return resonance.hasFission(); };
+
   // add fission if it exists
-  if ( ranges::count_if(
-           table.resonances(),
-           [&] ( const auto& resonance )
-               { return resonance.hasFission(); } ) > 1 ) {
+  if ( ranges::count_if( table.resonances(), hasFission ) > 1 ) {
```
Comment (nathangibson14) [inline src/resonanceReconstruction/rmatrix/legacy/SpinGroupBase/src/makeReactionIdentifiers.hpp]: This would work without the `> 1`, but I can't decide if that's better or worse.

File: src/resonanceReconstruction/rmatrix/test/fromENDF.test.hpp [hunk 2]
```diff
@@ -2137,19 +2732,19 @@ SCENARIO( "fromENDF" ) {
...
       // particle pair
       const auto pair41 = channel41.particlePair();
       CHECK( 0.9986235 * 1.008664 == Approx( pair41.particle().mass().value ) );
-      CHECK( 1.0 * 1.602e-19 == Approx( pair41.particle().charge().value ) );
+      CHECK( 1.0 * 1.60217662e-19 == Approx( pair41.particle().charge().value ) );
       CHECK( 0.5 == Approx( pair41.particle().spin() ) );
       CHECK( +1 == pair41.particle().parity() );
       CHECK( 34.66863 * 1.008664 == Approx( pair41.residual().mass().value ) );
-      CHECK( 16.0 * 1.602e-19 == Approx( pair41.residual().charge().value ) );
+      CHECK( 16.0 * 1.60217662e-19 == Approx( pair41.residual().charge().value ) );
```
Comment (nathangibson14) [inline src/resonanceReconstruction/rmatrix/test/fromENDF.test.hpp:2747]: I really hope you used find and replace on these...

**Review by nathangibson14 — COMMENTED** [review]
Just need to compile it, otherwise looks good.  No meaningful comments.

File: src/resonanceReconstruction/rmatrix/legacy/SpinGroupBase/src/makeReactionIdentifiers.hpp (hunk 1 above)
Comment (whaeck) [reply src/resonanceReconstruction/rmatrix/legacy/SpinGroupBase/src/makeReactionIdentifiers.hpp]: This is actually wrong: it should be > 0.

Comment (whaeck) [reply src/resonanceReconstruction/rmatrix/legacy/SpinGroupBase/src/makeReactionIdentifiers.hpp]: I fixed this and verified all other uses of count_if: none are wrong.

**Review by jlconlin — APPROVED** [review]

**Review by jlconlin — APPROVED** [review]
